// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('register', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('register', async function() {
    await driver.get("https://rori4.github.io/selenium-practice/")
    await driver.manage().window().setRect({ width: 1920, height: 1055 })
    await driver.findElement(By.id("email")).sendKeys("email@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("123456")
    await driver.findElement(By.id("submit")).click()
  })
})
